#ifndef eng_vars_h_included
#define eng_vars_h_included
// 컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴

extern char *_Screen;
extern char *_Buffer;
extern char *_Texture1;
extern char *_Texture2;
extern char *_ShadeTable;
extern char *_PhongMap;

extern float *_DivTable;

extern int MinX;
extern int MaxX;
extern int MinY;
extern int MaxY;

extern int ScreenWidth;
extern int ScreenHeight;

extern float viewdistance;

extern float min_clip_z;
extern float max_clip_z;

extern float halfscreenwidth_vd;
extern float halfscreenheight_vd;

extern char PhongIntensity[129];

// 컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
#endif
