global blobtex : byte 
global phongshade : byte
global pmap : byte    
global palette1 : byte
global palette2 : byte
global cred_gfx : byte
global anim1 : byte   
global anim2 : byte   
global timeoutgfx : byte
global timeoutpal : byte
global theythought : byte
global wewere : byte  
global textpal : byte
global textpal2 : byte
global tex_a : byte   
global tex_b : byte   
global twirlmap : byte
global twirltex : byte
global twirlpal : byte
global background1 : byte
global gfxp1 : byte   
global gfxp2: byte    
global gfxp3: byte    
global gfxp4: byte    
global gfxpalette : byte
global bumpmap1 : byte
global regards : byte
global regardspal : byte
global lastlogo : byte
global lastpal : byte