#ifndef defines_h_included
#define defines_h_included
// 컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴

#define PI 3.1415926535
// size of sin/cos tables
#define TABLESIZE 4096

// Value for 3d->2d projection
#define PROJ_VALUE 256
#define PROJ_VALUE2 512

// for converting Z-values to int for radix sort
#define Z_MULT 1

// sObject.Flags
#define OBJECT_Active 1

// 컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
#endif
