                extrn   nms_init:near

                extrn   nms_exit:near

                extrn   nms_driverinit:near

                extrn   nms_driverexit:near

                extrn   nms_moduleinit:near

                extrn   nms_moduleexit:near

                extrn   nms_modulestart:near

                extrn   nms_modulestop:near

                extrn   nms_autosetup:near

                extrn   nms_manualsetup:near

                extrn   nms_activatesync:near

                extrn   nms_deactivatesync:near

		extrn 	nms_setmastervol:near

;컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴

                extrn   nms_error:dword

                extrn   nms_errors:dword

;컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴

                extrn   nms_jmp_tick:dword

                extrn   nms_jmp_row:dword

                extrn   nms_jmp_cmd:dword

                extrn   nms_jmp_end:dword

                extrn   nms_dummy:near

;컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴

                extrn   nms_modulepos:dword

;컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴

