#ifndef defines_h_included
#define defines_h_included
// 컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴

#define PI 3.1415926535
#define NULL 0
#define FALSE 0
#define TRUE 1
#define TABLESIZE 4096

// Object file header

#define OBJECT_HEADER 'OBJ0'

// for converting floats to int for bytesort

#define Z_MULT 1 /*256*/

// sObject.Flags

#define OBJECT_Active 1

// 컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
#endif
