 #ifndef scene_hpp_included
 #define scene_hpp_included
 // -------------------------------------------------------------------------

 // #include "node.hpp"
 // #include "camera.hpp"
 #include "map.hpp"

class c_SCENE
 {

// ---
public:
// ---

c_SCENE();
c_SCENE(int max_polys_on_screen);
~c_SCENE();

 // void Load3DS(char *filename);
 // void Render(void);
 // void SetCamera(c_CAMERA &c);
 // void SetBuffer(c_BITMAP &b);

// ---
private:
// ---

 // c_NODE &Nodes;
 // c_CAMERA &Camera;

 };

 // -------------------------------------------------------------------------
 #endif
